//
// EventseventIdsectorssectorIdsubsectorssubsectorIdSeats.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


public class EventseventIdsectorssectorIdsubsectorssubsectorIdSeats: JSONEncodable {
    public var ticketId: String?
    public var ticketStatus: String?
    public var ownerId: String?
    public var seatNumber: String?

    public init() {}

    // MARK: JSONEncodable
    func encodeToJSON() -> AnyObject {
        var nillableDictionary = [String:AnyObject?]()
        nillableDictionary["ticketId"] = self.ticketId
        nillableDictionary["ticketStatus"] = self.ticketStatus
        nillableDictionary["ownerId"] = self.ownerId
        nillableDictionary["seatNumber"] = self.seatNumber
        let dictionary: [String:AnyObject] = APIHelper.rejectNil(nillableDictionary) ?? [:]
        return dictionary
    }
}
