//
// InlineResponse2002Subsectors.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


public class InlineResponse2002Subsectors: JSONEncodable {
    public var subsectorId: String?
    public var name: String?
    public var hasTickets: Int32?

    public init() {}

    // MARK: JSONEncodable
    func encodeToJSON() -> AnyObject {
        var nillableDictionary = [String:AnyObject?]()
        nillableDictionary["subsectorId"] = self.subsectorId
        nillableDictionary["name"] = self.name
        nillableDictionary["hasTickets"] = self.hasTickets?.encodeToJSON()
        let dictionary: [String:AnyObject] = APIHelper.rejectNil(nillableDictionary) ?? [:]
        return dictionary
    }
}
