//
// InlineResponse2001MapCoordinates.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


public class InlineResponse2001MapCoordinates: JSONEncodable {
    public var sectorId: String?
    public var coordinate: String?
    public var shape: String?

    public init() {}

    // MARK: JSONEncodable
    func encodeToJSON() -> AnyObject {
        var nillableDictionary = [String:AnyObject?]()
        nillableDictionary["sectorId"] = self.sectorId
        nillableDictionary["coordinate"] = self.coordinate
        nillableDictionary["shape"] = self.shape
        let dictionary: [String:AnyObject] = APIHelper.rejectNil(nillableDictionary) ?? [:]
        return dictionary
    }
}
