//
// Sectors.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


public class Sectors: JSONEncodable {
    public var gates: [InlineResponse2001Gates]?
    public var map: InlineResponse2001Map?

    public init() {}

    // MARK: JSONEncodable
    func encodeToJSON() -> AnyObject {
        var nillableDictionary = [String:AnyObject?]()
        nillableDictionary["gates"] = self.gates?.encodeToJSON()
        nillableDictionary["map"] = self.map?.encodeToJSON()
        let dictionary: [String:AnyObject] = APIHelper.rejectNil(nillableDictionary) ?? [:]
        return dictionary
    }
}
